---
- name: install fish
  tags:
    - full-install
    - light-install
    - fish
  ansible.builtin.package:
    name: fish
    state: present
    update_cache: true
  become: true

- name: Check if oh-my-fish is installed
  tags:
    - full-install
    - light-install
    - fish
  ansible.builtin.stat:
    path: '/etc/omf.installed'
  register: omf

- name: Clone oh-my-fish repo
  tags:
    - full-install
    - light-install
    - fish
  ansible.builtin.git:
    version: master
    repo: 'https://github.com/oh-my-fish/oh-my-fish'
    dest: '/tmp/omf'
    clone: true
  when: not omf.stat.exists

- name: Install oh-my-fish
  tags:
    - full-install
    - light-install
    - fish
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  ansible.builtin.command: /tmp/omf/bin/install -y --offline --noninteractive
  when: not omf.stat.exists

- name: change user shell to fish
  tags:
    - full-install
    - light-install
    - fish
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/fish
  become: true