- name: install reflector
  tags:
    - full-install
    - light-install
    - packages
  package:
    name: reflector
  become: true
  when: ansible_distribution == "Archlinux"

- name: update pacman mirrorlist
  tags:
    - full-install
    - light-install
    - packages
  script: choose-mirror.sh
  become: true
  when: ansible_distribution == "Archlinux"

- name: copy file pacman.conf to /etc
  tags:
    - full-install
    - light-install
    - packages
  copy:
    src: pacman.conf
    dest: /etc
    owner: root
    group: root
    mode: 0644
  become: true
  when: ansible_distribution == "Archlinux"

- name: Set intel variable when distribution is Archlinux (if necessary)
  tags:
    - full-install
    - light-install
    - packages
  set_fact:
    intel: intel-ucode
  when: ansible_distribution == "Archlinux" and "GenuineIntel" in ansible_processor

- name: Set intel variable when distribution is Ubuntu (if necessary)
  tags:
    - full-install
    - light-install
    - packages
  set_fact:
    intel: intel-acm
  when: ansible_distribution == "Ubuntu" and "GenuineIntel" in ansible_processor

- name: Install microcode updates for intel (if necessary)
  tags:
    - full-install
    - light-install
    - packages
  package:
    name: "{{ intel }}"
    state: present
    update_cache: true
  become: true
  when: '"GenuineIntel" in ansible_processor'

- name: Set amd variable when distribution is Archlinux (if necessary)
  tags:
    - full-install
    - light-install
    - packages
  set_fact:
    amd: amd-ucode
  when: ansible_distribution == "Archlinux" and "AuthenticAMD" in ansible_processor

- name: Set amd variable when distribution is Ubuntu (if necessary)
  tags:
    - processor-amd
    - never
  set_fact:
    amd: amd64-microcode
  when: ansible_distribution == "Ubuntu" and "AuthenticAMD" in ansible_processor

- name: Install microcode updates for amd (if necessary)
  tags:
    - processor-amd
    - never
  package:
    name: "{{ amd }}"
    state: present
    update_cache: true
  become: true
  when: '"AuthenticAMD" in ansible_processor'
- name: Install nvidia drivers
  tags:
    - nvidia
    - never
  package:
    name: nvidia
    state: present
  when: ansible_distribution == "Archlinux"
  become: true

- name: remove packages
  tags:
    - full-install
    - light-install
    - packages
  package:
    name:
      - arch-install-scripts
      - archinstall
      - vim
      - grml-zsh-config
      - zsh
    state: absent
    update_cache: no
  become: true
